---
### Compile IDP snapshot

- name: IDP SNAPSHOT | Check for java-identity-provider/idp-distribution
  local_action: stat path={{playbook_dir}}/java-identity-provider/idp-distribution/target
  become: no
  register: stat_local_snapshot

- name: IDP SNAPSHOT | Local distribution found, copying it to /tmp
  copy:
    src: "{{ item }}"
    dest: /tmp
  with_fileglob:
    - java-identity-provider/idp-distribution/target/shibboleth-identity-provider-*.tar.gz
  when: stat_local_snapshot.stat.exists

- name: IDP SNAPSHOT | git, maven
  package: name={{ item }} state=present
  with_items:
    - git
    - maven
  when: stat_local_snapshot.stat.exists == false

- name: IDP SNAPSHOT | Checkout snapshot from Git
  git:
    repo: 'https://git.shibboleth.net/git/java-identity-provider'
    dest: "/tmp/idp_snapshot"
  when: stat_local_snapshot.stat.exists == false

- name: IDP SNAPSHOT | Compile and build distribution package
  shell: mvn -f idp-parent/pom.xml clean package
  args:
    chdir: "/tmp/idp_snapshot"
    executable: /bin/bash
  become: yes
  when: stat_local_snapshot.stat.exists == false

- name: IDP SNAPSHOT | Copy complied distribution package to /tmp
  copy:
    src: "{{ item }}"
    dest: /tmp
    remote_src: True
  with_fileglob:
    - /tmp/idp_snapshot/idp-distribution/target/shibboleth-identity-provider-*.tar.gz
  when: stat_local_snapshot.stat.exists == false
