- hosts: app
  remote_user: vagrant
  become: yes
  vars:
    remote_user_home: /home/vagrant
  roles:
    - cmprescott.xml
    - { role: keystore }
    - { role: CSC-IT-Center-for-Science.mariadb, mariadb_root_password: testpass }
    - { role: CSC-IT-Center-for-Science.jetty }
    - { role: CSC-IT-Center-for-Science.shibboleth-idp, scope: csc.fi, port: 8443, bport: 8444, keystore_password: testpword }
    - { role: keystore, idp: true, keystore_password: testpword }

    - { role: oidc-extension, build_user: vagrant, idp_home: /opt/shibboleth-idp, environment_file: /etc/default/shibboleth-idp }
  
  tasks:
    - name: initial packages
      yum: name={{ item }} state=present
      with_items:
        - nano
        - unzip
